config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :sales do
    resources :products
  end
  root 'sales#index'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :sale
end

app/models/sale.rb
class Sale < ActiveRecord::Base
    has_many :products
    def name 
        client
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_sale

  # GET /products
  # GET /products.json
  def index
    #@products = Product.all
   # @products = Product.where(sale_id: params[:sale_id]).all
    @products = @sale.products.all   

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end
  

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
   # @product = Product.new(product_params)
    @product = @sale.products.new(product_params)


    respond_to do |format|
      if @product.save        
        format.html { redirect_to sale_products_path(@sale, @product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to sale_products_path(@sale, @product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to sale_products_path(@sale, @product), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :amount, :value, :sale_id)
    end


    def set_sale
      @sale = Sale.find(params[:sale_id])
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    #@sales = Sale.all
    @sales = Sale.paginate(page: params[:page], per_page: 2)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
    
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:client, :desc,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Shopping List', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        
      </div>
    </div>
  </nav>

  <main class="container" role="main">
    <%= yield %>
  </main>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for([@sale, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', sale_product_path(@sale, @product) %> |
<%= link_to 'Back', sale_products_path(@sale) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.amount %></td>
        <td><%= product.sale.name %></td>
        <td><%= link_to 'Show', sale_product_path(@sale, product) %></td>  
        <td><%= link_to 'Edit', edit_sale_product_path(@sale, product) %></td>      
        <td><%= link_to 'Destroy', sale_product_path(@sale, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_sale_product_path(@sale) %>
<%= link_to 'Back', sale_path(@sale) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_products_path(@sale) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @product.amount %>
</p>


<p>
  <strong>Sale:</strong>
  <%= @product.sale.client %>
</p>

<%= link_to 'Edit', edit_sale_product_path(@sale, @product) %> |
<%= link_to 'Back', sale_products_path(@sale) %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Client %><br>
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :Desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :Buy %><br>
    <%= f.check_box :status, {}, "Close", "Open" %> <br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
   
<% end %>

app/views/sales/edit.html.erb
<h1>Lista de Compras</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping List</h1>

<table class="table">
  <thead>
    <tr>
      <th>Client</th>
      <th>Desc</th>
      <th>Buy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.client %></td>
        <td><%= sale.desc %></td>
        <td><%= sale.status %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New Shopping List', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @sale.client %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @sale.desc %>
</p>
<p>
  <strong>Buy:</strong>
  <%= @sale.status %>
</p>


<%= link_to_if  @sale.status!="Close",'Produtos', sale_products_path(@sale)  %>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>